language: objective-c

# we do not use CocoaPods, so override install:
install: echo "Not everyone uses CocoaPods"

xcode_project: FSMegaInfo.xcodeproj

script:
  - xcodebuild || (./configure && make && make check)

compiler:
  - clang
  - gcc
