---
name: cooljeanius/FSMegaInfo
on:
  push:
    branches:
      - "**/*"
  pull_request:
jobs:
  test:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are
        # currently unsupported
        # 'compiler' was not transformed because there is no suitable equivalent
        # in GitHub Actions
      - run: sync && echo "Not everyone uses CocoaPods" && sleep 1
      - run: |
          xcodebuild || \
            (./configure && make && (make check || xcodebuild -target Test || Tests/Test.py || (test -x "$(which flake8)" && flake8 Tests/Test.py) || stat Tests/Test.py))
      - name: Debug failure
        if: "${{ failure() }}"
        run: |
          (test -r /usr/include/sys/vnode.h && cat /usr/include/sys/vnode.h) \
            || (test -r Tests/test-suite.log && cat Tests/test-suite.log) \
            || (test -r config.log && cat config.log)
    strategy:
      matrix:
        compiler:
          - clang
          - gcc
